# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\facultate\Anul III\Sem I\BD\TEMA\tema\modifyAnime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sl

class Ui_AnimeModifyWindow(object):

    def modify(self):
        mn = self.comboBox_2.currentText()
        con = sl.connect('TEMA.db')
        cursor = con.cursor()
        cursor.execute('Select anime_id FROM Anime_List WHERE anime_name=?', (mn,))
        results = cursor.fetchall()
        mid = results[0][0]
        print(mid)
        status = self.comboBox_5.currentText()
        score = self.comboBox.currentText()
        chr = self.lineEdit_5.text()
        print(status)
        cursor.execute('UPDATE Anime SET status=? WHERE anime_id=?', (status, mid,))
        con.commit()
        cursor.execute('UPDATE Anime SET score=? WHERE anime_id=?', (score, mid,))
        con.commit()
        cursor.execute('UPDATE Anime SET eps_watched=? WHERE anime_id=?', (chr, mid,))
        con.commit()

    def delete(self):
        mn=self.comboBox_2.currentText()
        con=sl.connect('TEMA.db')
        cursor=con.cursor()
        cursor.execute('Select anime_id FROM Anime_List WHERE anime_name=?',(mn,))
        results=cursor.fetchall()
        mid=results[0][0]
        print(mid)
        cursor.execute('DELETE FROM Anime_List WHERE anime_id=?',(mid,))
        cursor.execute('DELETE FROM Anime WHERE anime_id=?', (mid,))
        con.commit()
    def setupUi(self, AnimeModifyWindow,MainWindow):
        AnimeModifyWindow.setObjectName("MainWindow")
        AnimeModifyWindow.resize(805, 700)
        AnimeModifyWindow.setMinimumSize(QtCore.QSize(805, 700))
        AnimeModifyWindow.setMaximumSize(QtCore.QSize(805, 700))
        AnimeModifyWindow.setStyleSheet("background-color: rgb(151, 232, 255);")
        self.centralwidget = QtWidgets.QWidget(AnimeModifyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 230, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 340, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.modify)
        self.pushButton.setGeometry(QtCore.QRect(180, 480, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.clicked.connect(self.delete)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 480, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(270, 160, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(280, 350, 211, 41))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(280, 250, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(240, 40, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(1, "")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 0, 31, 28))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background:rgb(151, 232, 255);\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\facultate\\Anul III\\Sem I\\BD\\geo\\tema\\resources/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        AnimeModifyWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AnimeModifyWindow)
        self.statusbar.setObjectName("statusbar")
        AnimeModifyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AnimeModifyWindow)
        QtCore.QMetaObject.connectSlotsByName(AnimeModifyWindow)
        con = sl.connect('TEMA.db')
        cursor2 = con.cursor()
        cursor2.execute("SELECT name  FROM Anime")
        results2 = cursor2.fetchall()
        for r in results2:
            self.comboBox_2.addItem(r[0])

    def retranslateUi(self,AnimeModifyWindow):
        _translate = QtCore.QCoreApplication.translate
        AnimeModifyWindow.setWindowTitle(_translate("AnimeModifyWindow", "AnimeModifyWindow"))
        self.label.setText(_translate("AnimeModifyWindow", "Select Anime"))
        self.label_2.setText(_translate("AnimeModifyWindow", "Status"))
        self.label_3.setText(_translate("AnimeModifyWindow", "Episodes watched"))
        self.label_4.setText(_translate("AnimeModifyWindow", "Score"))
        self.pushButton.setText(_translate("AnimeModifyWindow", "Modify"))
        self.pushButton_2.setText(_translate("AnimeModifyWindow", "Delete"))
        self.comboBox_5.setItemText(0, _translate("AnimeModifyWindow", "Watching"))
        self.comboBox_5.setItemText(1, _translate("AnimeModifyWindow", "Completed"))
        self.comboBox_5.setItemText(2, _translate("AnimeModifyWindow", "OnHold"))
        self.comboBox_5.setItemText(3, _translate("AnimeModifyWindow", "Dropped"))
        self.comboBox_5.setItemText(4, _translate("AnimeModifyWindow", "PlanToWatch"))
        self.comboBox.setItemText(0, _translate("AnimeModifyWindow", "1"))
        self.comboBox.setItemText(1, _translate("AnimeModifyWindow", "2"))
        self.comboBox.setItemText(2, _translate("AnimeModifyWindow", "3"))
        self.comboBox.setItemText(3, _translate("AnimeModifyWindow", "4"))
        self.comboBox.setItemText(4, _translate("AnimeModifyWindow", "5"))
        self.comboBox.setItemText(5, _translate("AnimeModifyWindow", "6"))
        self.comboBox.setItemText(6, _translate("AnimeModifyWindow", "7"))
        self.comboBox.setItemText(7, _translate("AnimeModifyWindow", "8"))
        self.comboBox.setItemText(8, _translate("AnimeModifyWindow", "9"))
        self.comboBox.setItemText(9, _translate("AnimeModifyWindow", "10"))