# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\facultate\Anul III\Sem I\BD\TEMA\tema\modifyManga.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sl

class Ui_MangaModifyWindow(object):
    def modify(self):
        mn = self.comboBox_2.currentText()
        con = sl.connect('TEMA.db')
        cursor = con.cursor()
        cursor.execute('Select manga_id FROM Manga_List WHERE manga_name=?', (mn,))
        results = cursor.fetchall()
        mid = results[0][0]
        print(mid)
        status=self.comboBox_5.currentText()
        score=self.comboBox.currentText()
        chr=self.lineEdit_5.text()
        print(status)
        cursor.execute('UPDATE Manga SET status=? WHERE manga_id=?', (status,mid,))
        con.commit()
        cursor.execute('UPDATE Manga SET score=? WHERE manga_id=?', (score, mid,))
        con.commit()
        cursor.execute('UPDATE Manga SET chapters_read=? WHERE manga_id=?', (chr, mid,))
        con.commit()
    def delete(self):
        mn=self.comboBox_2.currentText()
        con=sl.connect('TEMA.db')
        cursor=con.cursor()
        cursor.execute('Select manga_id FROM Manga_List WHERE manga_name=?',(mn,))
        results=cursor.fetchall()
        mid=results[0][0]
        print(mid)
        cursor.execute('DELETE FROM Manga_List WHERE manga_id=?',(mid,))
        cursor.execute('DELETE FROM Manga WHERE manga_id=?',(mid,))
        con.commit()
    def home(self, main_win, current_win):
        current_win.close()
        main_win.show()

    def setupUi(self, MangaModifyWindow,MainWindow):
        MangaModifyWindow.setObjectName("MainWindow")
        MangaModifyWindow.resize(805, 700)
        MangaModifyWindow.setMinimumSize(QtCore.QSize(805, 700))
        MangaModifyWindow.setMaximumSize(QtCore.QSize(805, 700))
        MangaModifyWindow.setStyleSheet("background-color: rgb(151, 232, 255);")
        self.centralwidget = QtWidgets.QWidget(MangaModifyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.clicked.connect(self.delete)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 540, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 190, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.modify)
        self.pushButton.setGeometry(QtCore.QRect(200, 540, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(350, 390, 211, 41))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(350, 290, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 70, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(1, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 70, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 0, 31, 28))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background:rgb(151, 232, 255);\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\facultate\\Anul III\\Sem I\\BD\\geo\\tema\\resources/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 390, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(320, 180, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        MangaModifyWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MangaModifyWindow)
        self.statusbar.setObjectName("statusbar")
        MangaModifyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MangaModifyWindow)
        QtCore.QMetaObject.connectSlotsByName(MangaModifyWindow)
        con = sl.connect('TEMA.db')
        cursor2 = con.cursor()
        cursor2.execute("SELECT name  FROM Manga")
        results2 = cursor2.fetchall()
        for r in results2:
            self.comboBox_2.addItem(r[0])


    def retranslateUi(self, MangaModifyWindow):
        _translate = QtCore.QCoreApplication.translate
        MangaModifyWindow.setWindowTitle(_translate("MangaModifyWindow", "MangaModifyWindow"))
        self.pushButton_2.setText(_translate("MangaModifyWindow", "Delete"))
        self.label_2.setText(_translate("MangaModifyWindow", "Status"))
        self.label_3.setText(_translate("MangaModifyWindow", "Chapters read"))
        self.pushButton.setText(_translate("MangaModifyWindow", "Modify"))
        self.comboBox.setItemText(0, _translate("MangaModifyWindow", "1"))
        self.comboBox.setItemText(1, _translate("MangaModifyWindow", "2"))
        self.comboBox.setItemText(2, _translate("MangaModifyWindow", "3"))
        self.comboBox.setItemText(3, _translate("MangaModifyWindow", "4"))
        self.comboBox.setItemText(4, _translate("MangaModifyWindow", "5"))
        self.comboBox.setItemText(5, _translate("MangaModifyWindow", "6"))
        self.comboBox.setItemText(6, _translate("MangaModifyWindow", "7"))
        self.comboBox.setItemText(7, _translate("MangaModifyWindow", "8"))
        self.comboBox.setItemText(8, _translate("MangaModifyWindow", "9"))
        self.comboBox.setItemText(9, _translate("MangaModifyWindow", "10"))
        self.label.setText(_translate("MangaModifyWindow", "Select Manga"))
        self.label_4.setText(_translate("MangaModifyWindow", "Score"))
        self.comboBox_5.setItemText(0, _translate("MangaModifyWindow", "Reading"))
        self.comboBox_5.setItemText(1, _translate("MangaModifyWindow", "Completed"))
        self.comboBox_5.setItemText(2, _translate("MangaModifyWindow", "OnHold"))
        self.comboBox_5.setItemText(3, _translate("MangaModifyWindow", "Dropped"))
        self.comboBox_5.setItemText(4, _translate("MangaModifyWindow", "PlanToRead"))