# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\1_university\Anul III\1_Sem1\BD\BD-Tema\newAuthor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sl

class Ui_AuthorWindow(object):

    def discard(self):
        self.firstNameEdit.clear()
        self.lastNameEdit.clear()
        self.dateEdit.clear()

    def add(self,current_win):

        # TODO
        con=sl.connect('TEMA.DB')
        cursor = con.cursor()

        cursor.execute("SELECT author_id  FROM Author")

        results = cursor.fetchall()
        max=results[0][0]
        print(max)
        for r in results:
            if(max<r[0]):
                max=r[0]
        print(max)
        max=max+1
        sql = 'INSERT INTO Author (author_id,first_name,last_name,date_of_birth) values( ?, ?,?,?)'
        data = [
            (max, self.firstNameEdit.text(), self.lastNameEdit.text(), self.dateEdit.text())
        ]
        with con:
            con.executemany(sql, data)
        current_win.close()

        '''
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MangaWindow()
        self.ui.setupUi(self.window, MangaWindow)
        self.window.show()
        '''
    def setupUi(self, AuthorWindow):
        # AUTHOR WINDOW
        AuthorWindow.setObjectName("AuthorWindow")
        AuthorWindow.resize(805, 700)
        AuthorWindow.setMinimumSize(QtCore.QSize(805, 700))
        AuthorWindow.setMaximumSize(QtCore.QSize(805, 700))
        AuthorWindow.setStyleSheet("background-color: rgb(151, 232, 255);")
        self.centralwidget = QtWidgets.QWidget(AuthorWindow)
        self.centralwidget.setObjectName("centralwidget")

        #FIRST NAME LABEL
        self.firstNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.firstNameLabel.setGeometry(QtCore.QRect(60, 250, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.firstNameLabel.setFont(font)
        self.firstNameLabel.setObjectName("firstNameLabel")

        # LAST NAME LABEL
        self.lastNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastNameLabel.setGeometry(QtCore.QRect(60, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.lastNameLabel.setFont(font)
        self.lastNameLabel.setObjectName("lastNameLabel")

        # BIRTHDAY LABEL
        self.birthdayLabel = QtWidgets.QLabel(self.centralwidget)
        self.birthdayLabel.setGeometry(QtCore.QRect(60, 340, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.birthdayLabel.setFont(font)
        self.birthdayLabel.setObjectName("birthdayLabel")


        # FIRST NAME LINE
        self.firstNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.firstNameEdit.setGeometry(QtCore.QRect(250, 240, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.firstNameEdit.setFont(font)
        self.firstNameEdit.setStyleSheet("QLineEdit{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.firstNameEdit.setText("")
        self.firstNameEdit.setObjectName("lineEdit")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(620, 610, 171, 61))
        self.addButton.clicked.connect(lambda: self.add(AuthorWindow))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.addButton.setObjectName("addButton")
        self.discardButton = QtWidgets.QPushButton(self.centralwidget)
        self.discardButton.setGeometry(QtCore.QRect(20, 610, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.discardButton.setFont(font)
        self.discardButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.discardButton.setObjectName("discardButton")
        self.discardButton.clicked.connect(self.discard)

        '''
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(260, 360, 110, 22))
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        '''

        self.dateEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(260, 360, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QLineEdit{\n"
                                        "    background: pink;\n"
                                        "    border: 2px solid rgb(151, 232, 255);\n"
                                        "    border-radius: 20px;\n"
                                        "}\n"
                                        "\n"
                                        "QLineEdit:focus{\n"
                                        "    border: 2px solid rgb(111, 165, 171);\n"
                                        "}\n"
                                        "")
        self.dateEdit.setText("")
        self.dateEdit.setObjectName("dateEdit")

        # LAST NAME EDIT
        self.lastNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lastNameEdit.setGeometry(QtCore.QRect(250, 300, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lastNameEdit.setFont(font)
        self.lastNameEdit.setStyleSheet("QLineEdit{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.lastNameEdit.setText("")
        self.lastNameEdit.setObjectName("lineEdit_2")

        AuthorWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AuthorWindow)
        self.statusbar.setObjectName("statusbar")
        AuthorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AuthorWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthorWindow)

    def retranslateUi(self, AuthorWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthorWindow.setWindowTitle(_translate("AuthorWindow", "AuthorWindow"))
        self.firstNameLabel.setText(_translate("AuthorWindow", "First Name"))
        self.lastNameLabel.setText(_translate("AuthorWindow", "Last Name"))
        self.birthdayLabel.setText(_translate("AuthorWindow", "Birthday"))
        self.addButton.setText(_translate("AuthorWindow", "Add"))
        self.discardButton.setText(_translate("AuthorWindow", "Discard"))