# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\1_university\Anul III\1_Sem1\BD\BD-Tema\newAnime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sl
class Ui_AnimeWindow(object):

    def discard(self):
        self.titleEdit.clear()
        self.totalNrEpEdit.clear()
        self.lineEdit_5.clear()
        self.scoreComboBox.setCurrentIndex(0)
        self.genreComboBox.setCurrentIndex(0)
        self.statusComboBox.setCurrentIndex(0)
        self.authorComboBox.setCurrentIndex(0)
        self.studioComboBox.setCurrentIndex(0)

    def addAnime(self):
        con = sl.connect('TEMA.DB')
        cursor = con.cursor()
        cursor.execute("SELECT anime_id  FROM Anime_List")
        results = cursor.fetchall()
        max = results[0][0]
        print(max)
        for r in results:
            if (max < r[0]):
                max = r[0]
        print(max)
        max = max + 1       # GENERARE ANIME_ID

        sql = 'INSERT INTO Anime_List (anime_id,anime_name) values( ?, ?)' # INSERARE IN TABELA ANIME_LIST
        data = [
            (max, self.titleEdit.text())
        ]
        with con:
            con.executemany(sql, data)

        # EXTRAGERE AUTHOR_ID IN FUNCTIE DE NUMELE DAT
        ln = self.authorComboBox.currentText()
        print(ln)
        cursor2 = con.cursor()
        cursor2.execute("SELECT author_id  FROM Author WHERE last_name=?", (ln,))
        aid = cursor2.fetchall()
        aidd = aid[0][0]
        print(aidd)

        # EXTRAGERE STUDIO_ID IN FUNCTIE DE NUMELE DAT
        sn=self.studioComboBox.currentText()
        cursor3 = con.cursor()
        cursor3.execute("SELECT studio_id  FROM Studio WHERE studio_name=?", (sn,))
        print(sn)
        sid = cursor3.fetchall()
        sidd = sid[0][0]
        print(sidd)

        sql2 = 'INSERT INTO Anime (name,genre,score,status,total_eps,eps_watched,anime_id,author_id,studio_id) values(?,?,?,?,?,?,?,?,?)'
        data2 = [
            (self.titleEdit.text(), self.genreComboBox.currentText(), self.scoreComboBox.currentText(),
             self.statusComboBox.currentText()
             , self.totalNrEpEdit.text(), self.lineEdit_5.text(), max, aidd,sidd)
        ]
        with con:
            con.executemany(sql2, data2)




    def home(self,main_win,current_win):                    #MA INTORC LA HOME
        current_win.close()
        main_win.show()


    def setupUi(self,AnimeWindow,MainWindow):
        #ANIME WINDOW
        AnimeWindow.setObjectName("AnimeWindow")
        AnimeWindow.resize(805, 700)
        AnimeWindow.setMinimumSize(QtCore.QSize(805, 700))
        AnimeWindow.setMaximumSize(QtCore.QSize(805, 700))
        AnimeWindow.setStyleSheet("background-color: rgb(151, 232, 255);")
        self.centralwidget = QtWidgets.QWidget(AnimeWindow)
        self.centralwidget.setObjectName("centralwidget")

        # TITLE LABEL
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(20, 50, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")

        #AUTHOR LABEL
        self.authorLabel = QtWidgets.QLabel(self.centralwidget)
        self.authorLabel.setGeometry(QtCore.QRect(20, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.authorLabel.setFont(font)
        self.authorLabel.setObjectName("authorLable")

        #GENRE LABEL
        self.genreLabel = QtWidgets.QLabel(self.centralwidget)
        self.genreLabel.setGeometry(QtCore.QRect(20, 190, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.genreLabel.setFont(font)
        self.genreLabel.setObjectName("genreLabel")

        #SCORE LABEL
        self.scoreLabel = QtWidgets.QLabel(self.centralwidget)
        self.scoreLabel.setGeometry(QtCore.QRect(20, 410, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.scoreLabel.setFont(font)
        self.scoreLabel.setObjectName("scoreLabel")

        # TITLE EDIT
        self.titleEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.titleEdit.setGeometry(QtCore.QRect(150, 40, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleEdit.setFont(font)
        self.titleEdit.setStyleSheet("QLineEdit{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.titleEdit.setText("")
        self.titleEdit.setObjectName("titleEdit")

        #   TOTAL NR OF EP EDIT
        self.totalNrEpEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalNrEpEdit.setText("")
        self.totalNrEpEdit.setGeometry(QtCore.QRect(150, 310, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalNrEpEdit.setFont(font)
        self.totalNrEpEdit.setStyleSheet("QLineEdit{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.totalNrEpEdit.setObjectName("lineEdit_3")

        # ADD TO LIST BUTTON
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.clicked.connect(self.addAnime)
        self.addButton.setGeometry(QtCore.QRect(610, 610, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.addButton.setObjectName("addButton")

        # DISCARD BUTTON
        self.discardButton = QtWidgets.QPushButton(self.centralwidget)
        self.discardButton.setGeometry(QtCore.QRect(20, 610, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.discardButton.setFont(font)
        self.discardButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.discardButton.setObjectName("discardButton")
        self.discardButton.clicked.connect(self.discard)

        #STUDIO LABEL
        self.studioLabel = QtWidgets.QLabel(self.centralwidget)
        self.studioLabel.setGeometry(QtCore.QRect(20, 140, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.studioLabel.setFont(font)
        self.studioLabel.setObjectName("studioLabel")

        #ADD TO FAV BUTTON
        '''
        self.addFavButton = QtWidgets.QPushButton(self.centralwidget)
        self.addFavButton.setGeometry(QtCore.QRect(20, 610, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.addFavButton.setFont(font)
        self.addFavButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.addFavButton.setObjectName("addFavButton")
'''
        # HOME BUTTON
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(0, 0, 31, 28))
        self.homeButton.clicked.connect(lambda: self.home(MainWindow,AnimeWindow))
        self.homeButton.setStyleSheet("QPushButton{\n"
"    background:rgb(151, 232, 255);\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources\\home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setObjectName("homeButton")


        self.scoreComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.scoreComboBox.setGeometry(QtCore.QRect(150, 420, 211, 41))
        self.scoreComboBox.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.scoreComboBox.setObjectName("scoreComboBox")
        self.scoreComboBox.addItem("")
        self.scoreComboBox.addItem("")
        self.scoreComboBox.addItem("")
        self.scoreComboBox.addItem("")
        self.scoreComboBox.addItem("")
        self.scoreComboBox.addItem("")
        self.scoreComboBox.addItem("")
        self.scoreComboBox.addItem("")
        self.scoreComboBox.addItem("")
        self.scoreComboBox.addItem("")



        # COMBOBOX AUTHOR
        self.authorComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.authorComboBox.setGeometry(QtCore.QRect(150, 90, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.authorComboBox.setFont(font)
        self.authorComboBox.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.authorComboBox.setObjectName("authorComboBox")


        # COMBOBOX STUDIO
        self.studioComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.studioComboBox.setGeometry(QtCore.QRect(150, 140, 451, 41))
        self.studioComboBox.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}\n"
"")
        self.studioComboBox.setObjectName("studioComboBox")



        # COMBO BOX 4
        self.genreComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.genreComboBox.setGeometry(QtCore.QRect(150, 200, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.genreComboBox.setFont(font)
        self.genreComboBox.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.genreComboBox.setObjectName("genreComboBox")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")
        self.genreComboBox.addItem("")

        # LABEL
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(20, 250, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")

        #COMBO BOX 5
        self.statusComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.statusComboBox.setGeometry(QtCore.QRect(150, 260, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.statusComboBox.setFont(font)
        self.statusComboBox.setStyleSheet("QComboBox{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    \n"
"    selection-color:pink;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: pink;\n"
"    color:black;\n"
" \n"
"    selection-background-color: rgb(206, 164, 196);\n"
"    selection-color: black;\n"
"}")
        self.statusComboBox.setObjectName("statusComboBox")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")

        # EP WATCHED LABEL
        self.epWatchedLabel = QtWidgets.QLabel(self.centralwidget)
        self.epWatchedLabel.setGeometry(QtCore.QRect(20, 350, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.epWatchedLabel.setFont(font)
        self.epWatchedLabel.setObjectName("epWatchedLabel")

        # TOTAL NR EP LABEL
        self.totalNrEpLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalNrEpLabel.setGeometry(QtCore.QRect(20, 300, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(12)
        self.totalNrEpLabel.setFont(font)
        self.totalNrEpLabel.setObjectName("totalNrEpLabel")

        # EDIT
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 360, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        AnimeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AnimeWindow)
        self.statusbar.setObjectName("statusbar")
        AnimeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AnimeWindow)
        QtCore.QMetaObject.connectSlotsByName(AnimeWindow)

        con = sl.connect('TEMA.db')

        cursor = con.cursor()

        cursor.execute("SELECT studio_name  FROM Studio")

        results = cursor.fetchall()

        for r in results:
            self.studioComboBox.addItem(r[0])

        cursor2 = con.cursor()

        cursor2.execute("SELECT last_name  FROM Author")

        results2 = cursor2.fetchall()

        for r in results2:
            self.authorComboBox.addItem(r[0])

    def retranslateUi(self, AnimeWindow):
        _translate = QtCore.QCoreApplication.translate
        AnimeWindow.setWindowTitle(_translate("AnimeWindow", "AnimeWindow"))
        self.titleLabel.setText(_translate("AnimeWindow", "Title"))
        self.authorLabel.setText(_translate("AnimeWindow", "Author"))
        self.genreLabel.setText(_translate("AnimeWindow", "Genre"))
        self.scoreLabel.setText(_translate("AnimeWindow", "Score"))
        self.addButton.setText(_translate("AnimeWindow", "Add to List"))
        self.discardButton.setText(_translate("AnimeWindow", "Discard"))
        self.studioLabel.setText(_translate("AnimeWindow", "Studio"))
        self.scoreComboBox.setItemText(0, _translate("AnimeWindow", "1"))
        self.scoreComboBox.setItemText(1, _translate("AnimeWindow", "2"))
        self.scoreComboBox.setItemText(2, _translate("AnimeWindow", "3"))
        self.scoreComboBox.setItemText(3, _translate("AnimeWindow", "4"))
        self.scoreComboBox.setItemText(4, _translate("AnimeWindow", "5"))
        self.scoreComboBox.setItemText(5, _translate("AnimeWindow", "6"))
        self.scoreComboBox.setItemText(6, _translate("AnimeWindow", "7"))
        self.scoreComboBox.setItemText(7, _translate("AnimeWindow", "8"))
        self.scoreComboBox.setItemText(8, _translate("AnimeWindow", "9"))
        self.scoreComboBox.setItemText(9, _translate("AnimeWindow", "10"))
        self.genreComboBox.setCurrentText(_translate("AnimeWindow", "Action"))
        self.genreComboBox.setItemText(0, _translate("AnimeWindow", "Action"))
        self.genreComboBox.setItemText(1, _translate("AnimeWindow", "Adventure"))
        self.genreComboBox.setItemText(2, _translate("AnimeWindow", "Comedy"))
        self.genreComboBox.setItemText(3, _translate("AnimeWindow", "Drama"))
        self.genreComboBox.setItemText(4, _translate("AnimeWindow", "Slice of Life"))
        self.genreComboBox.setItemText(5, _translate("AnimeWindow", "Fantasy"))
        self.genreComboBox.setItemText(6, _translate("AnimeWindow", "Magic"))
        self.genreComboBox.setItemText(7, _translate("AnimeWindow", "Supernatural"))
        self.genreComboBox.setItemText(8, _translate("AnimeWindow", "Horror"))
        self.genreComboBox.setItemText(9, _translate("AnimeWindow", "Mystery"))
        self.genreComboBox.setItemText(10, _translate("AnimeWindow", "Psychological"))
        self.genreComboBox.setItemText(11, _translate("AnimeWindow", "Romance"))
        self.genreComboBox.setItemText(12, _translate("AnimeWindow", "Sci-Fi"))
        self.statusLabel.setText(_translate("AnimeWindow", "Status"))
        self.statusComboBox.setItemText(0, _translate("AnimeWindow", "Watching"))
        self.statusComboBox.setItemText(1, _translate("AnimeWindow", "Completed"))
        self.statusComboBox.setItemText(2, _translate("AnimeWindow", "OnHold"))
        self.statusComboBox.setItemText(3, _translate("AnimeWindow", "Dropped"))
        self.statusComboBox.setItemText(4, _translate("AnimeWindow", "PlanToWatch"))
        self.epWatchedLabel.setText(_translate("AnimeWindow", "Eps Watched"))
        self.totalNrEpLabel.setText(_translate("AnimeWindow", "Total nr of eps"))